paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
kramdown:
   auto_ids: true
#gfm_quirks:
lsi:         false


disqus: akash
google_analytics: akash
title: Akash

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Akash

description: Notes on experiments
author:
  name: akash
  email: akashsharmaa@gmail
  github: akash-git
  twitter: aakash1979
  linkedin: aakash1979
  bio: Coder, notes on experiments!

categories_path: categories.html
tags_path: tags.html

BASE_PATH:

gems:
  - jekyll-paginate