paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
kramdown:
  auto_ids: true
#gfm_quirks:
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

#lsi:         false


disqus: www-akashsharma-me
google_analytics: akash
title: Akash

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Akash

description: Notes on experiments
author:
  name: akash
  email: akashsharmaa@gmail
  github: akash-git
  twitter: aakash1979
  linkedin: aakash1979
  bio: Coder, notes on experiments!

categories_path: categories.html
tags_path: tags.html

BASE_PATH:

gems:
  - jekyll-paginate